### ISSUE TITLE
dark mode and search icon disappeared

### ISSUE THREAD

**Issue by eunhyekim-grace** [byanko55/jekyll-theme-satellite#40]
Hello, first of all thank you for the great project :)
While I was setting the blog, I find out that dark mode icon and search icon has disappeared. 
I saw the codes are still there but couldn't find where the errors come from. It would be great if you could check it. 

Additionally, do you mind if I change the email link navigation change using mailto? With original code when you click email icon on the github.io page it shows 404 page error, but with mailto library email sending page pops up. :)

I look forward to hearing from you soon. Have a great day. 
Best, 
Grace

**Comment by byanko55** [comment]
Thanks for the reports @eunhyekim-grace.

I guess you could not see the sidebar buttons on a small desktop screen. I have fixed that issue in #41, along with the problem related to the e-mail link. 

If it's not fully resolved, please reply below with a screenshot so that I can look into where you have been stuck.

**Comment by eunhyekim-grace** [comment]
Oh,, the problems are clearly solved.
Tysm again for the great work :)
